# Generated by Django 5.2.5 on 2025-10-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
